### ISSUE TITLE
Get items breaks

### ISSUE THREAD

**Issue by goegol** [Dielee/tgtg-python#2]
Hi again!

When i try to get the items i got error:

```
Traceback (most recent call last):
  File "/home/goegol/tgtg_get_tokens.py", line 13, in <module>
    client.get_items()
  File "/root/.local/share/virtualenvs/goegol-54Koo1qd/lib/python3.9/site-packages/tgtg/__init__.py", line 181, in get_items
    self.login()
  File "/root/.local/share/virtualenvs/goegol-54Koo1qd/lib/python3.9/site-packages/tgtg/__init__.py", line 158, in login
    raise TgtgPollingError("Max retries (2 Minutes) reached. Try again.")
tgtg.exceptions.TgtgPollingError: Max retries (2 Minutes) reached. Try again.
```

the python code i use is:
```
from tgtg import TgtgClient
email = "mail@example.com"

client = TgtgClient(email=email)

client.get_items()
```

**Comment by TanguyOrtegat** [comment]
you need to valideate your login with your email within the 2 minutes

**Comment by Dielee** [comment]
My fault, please try again!

**Comment by goegol** [comment]
Its working, thnx!!
